claude_code:
  binary_path: claude
  model: claude-sonnet-4-5-20250929
  night_start_hour: 1
  night_end_hour: 9
  threshold_day: 20.0
  threshold_night: 80.0
  usage_command: claude /usage

git:
  use_remote_repo: true
  remote_repo_url: git@github.com:TimeLovercc/sleepless-agent.git
  auto_create_repo: true

agent:
  workspace_root: ./workspace
  task_timeout_seconds: 1800

multi_agent_workflow:
  planner:
    enabled: true
    max_turns: 3
  worker:
    enabled: true
    max_turns: 3
  evaluator:
    enabled: true
    max_turns: 3

auto_generation:
  enabled: true
  prompts:
    - name: refine_focused
      prompt: |-
        The workspace has multiple ongoing projects and tasks that need attention.

        ## Current State
        - Active tasks: {task_count} ({pending_count} pending, {in_progress_count} in progress)
        - Many tasks are already in progress or pending

        ## Recent Work & Context
        {recent_work}

        ## Task Generation
        Generate ONE REFINE task to continue or improve existing work:
        - Complete partial/incomplete tasks mentioned above
        - Follow up on outstanding items and recommendations
        - Enhance or improve existing projects in the workspace
        - Fix issues or improve quality of current work
        - Add missing components to existing implementations
        - Expand documentation or analysis from previous tasks

        IMPORTANT: Your response MUST start with [REFINE] followed by a specific, actionable task description in 1-2 sentences.

        Focus on completing or improving what already exists in the workspace rather than starting new projects.
      weight: 0.45
    - name: balanced
      prompt: |-
        Review the workspace state and generate a valuable task.

        ## Current State
        - Active tasks: {task_count} ({pending_count} pending, {in_progress_count} in progress)

        ## Recent Work & Context
        {recent_work}

        ## Task Generation
        Generate ONE valuable task (NEW or REFINE):
        - For REFINE: improve existing work, complete partial tasks, enhance current projects
        - For NEW: create something useful, interesting, or educational

        Task categories to consider:
        - Software development (applications, scripts, tools, APIs)
        - Data analysis and visualization projects
        - Research and documentation (technical guides, comparisons, best practices)
        - Creative writing (stories, tutorials, technical articles)
        - System design and architecture documents
        - Educational content and examples
        - Automation and productivity improvements
        - Analysis and evaluation reports

        IMPORTANT: Prefix your response with [NEW] or [REFINE] followed by a specific, actionable task description in 1-2 sentences.
      weight: 0.35
    - name: new_friendly
      prompt: |-
        Generate an interesting and valuable task for the workspace.

        ## Current State
        - Active tasks: {task_count} ({pending_count} pending, {in_progress_count} in progress)
        - Few tasks in queue - good time for new projects!

        ## Task Generation
        Generate ONE innovative task that creates value.

        Areas to explore:
        - Build practical tools and utilities
        - Create educational content and tutorials
        - Develop software applications or scripts
        - Write comprehensive documentation or guides
        - Design systems and architectures
        - Analyze and compare technologies or approaches
        - Generate creative content (technical writing, examples)
        - Research and summarize complex topics
        - Create data visualizations or analysis
        - Develop proof-of-concepts or experiments

        Can be NEW (fresh project) or REFINE (improve existing work) - choose what would be most valuable.

        IMPORTANT: Prefix your response with [NEW] or [REFINE] followed by a specific, actionable task description in 1-2 sentences.
      weight: 0.20

